### ISSUE TITLE
not able to run npm install

### ISSUE THREAD

**Issue by kratosmat** [boundlessgeo/sdk#760]
Hi all,
I am not able to install the sdk from source, I receive the following errors:

kratos@kratos-almaviva:~/Developments/AMA/sdk$ npm install
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)

> canvas@1.6.7 install /home/kratos/Developments/AMA/sdk/node_modules/canvas
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
Package cairo was not found in the pkg-config search path.
Perhaps you should add the directory containing `cairo.pc'
to the PKG_CONFIG_PATH environment variable
No package 'cairo' found
gyp: Call to './util/has_lib.sh freetype' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/kratos/.nvm/versions/node/v9.2.1/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at ChildProcess.emit (events.js:159:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Linux 4.8.0-54-generic
gyp ERR! command "/home/kratos/.nvm/versions/node/v9.2.1/bin/node" "/home/kratos/.nvm/versions/node/v9.2.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/kratos/Developments/AMA/sdk/node_modules/canvas
gyp ERR! node -v v9.2.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@1.6.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas@1.6.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kratos/.npm/_logs/2017-12-09T20_06_01_795Z-debug.log

Could anyone help me?

**Comment by bartvde** [comment]
make sure you have the dependencies for the canvas package installed: https://github.com/boundlessgeo/sdk/blob/master/DEVELOPING.md

**Comment by kratosmat** [comment]
Hi,
thanks for the quick answer.
You were right, I didn't have installed node-gyp. 

However, after npm install I try npm run build:examples and npm start, but I receive the following errors and I am not able to see the examples.



kratos@kratos-almaviva:~/Developments/AMA/sdk$ npm start

> @boundlessgeo/sdk@2.2.0 start /home/kratos/Developments/AMA/sdk
> webpack-dev-server --config webpack-dev-server.config.js --open --open-page 'build/examples'

Project is running at http://localhost:3000/
webpack output is served from /
Content not from webpack is served from ./
Hash: dbd677935bfe59206046
Version: webpack 3.8.1
Time: 12463ms
                                                         Asset       Size                                                                Chunks                    Chunk Names
                        build/examples/wfst/wfst.bundle.js.map    3.85 MB                                                                     0  [emitted]         wfst
                            build/examples/wfst/wfst.bundle.js    3.54 MB                                                                     0  [emitted]  [big]  wfst
                  build/examples/mb-bright/mb-bright.bundle.js    3.33 MB                                                                     2  [emitted]  [big]  mb-bright
                    build/examples/bookmark/bookmark.bundle.js    3.33 MB                                                                     3  [emitted]  [big]  bookmark
              build/examples/geolocation/geolocation.bundle.js    3.33 MB                                                                     4  [emitted]  [big]  geolocation
                    build/examples/realtime/realtime.bundle.js    3.31 MB                                                                     5  [emitted]  [big]  realtime
            build/examples/paint-change/paint-change.bundle.js    3.33 MB                                                                     6  [emitted]  [big]  paint-change
                      build/examples/legends/legends.bundle.js    3.33 MB                                                                     7  [emitted]  [big]  legends
                        build/examples/filter/filter.bundle.js    3.32 MB                                                                     8  [emitted]  [big]  filter
            build/examples/export-image/export-image.bundle.js     3.3 MB                                                                     9  [emitted]  [big]  export-image
                      build/examples/drawing/drawing.bundle.js    3.32 MB                                                                    10  [emitted]  [big]  drawing
                          build/examples/basic/basic.bundle.js    3.34 MB                                                                    11  [emitted]  [big]  basic
                build/examples/upload-map/upload-map.bundle.js    3.31 MB                                                                    12  [emitted]  [big]  upload-map
    build/examples/sprite-animation/sprite-animation.bundle.js    3.31 MB                                                                    13  [emitted]  [big]  sprite-animation
                        build/examples/popups/popups.bundle.js    3.32 MB                                                                    14  [emitted]  [big]  popups
          build/examples/feature-table/feature-table.bundle.js    3.32 MB                                                                    15  [emitted]  [big]  feature-table
              build/examples/basic-wgs84/basic-wgs84.bundle.js    3.32 MB                                                                    16  [emitted]  [big]  basic-wgs84
                      build/examples/sprites/sprites.bundle.js     3.3 MB                                                                    17  [emitted]  [big]  sprites
                    build/examples/rotating/rotating.bundle.js     3.3 MB                                                                    18  [emitted]  [big]  rotating
                build/examples/layer-list/layer-list.bundle.js    3.34 MB                                                                    19  [emitted]  [big]  layer-list
                build/examples/clustering/clustering.bundle.js    3.31 MB                                                                    20  [emitted]  [big]  clustering
                                        build/examples/sdk.css    9.21 kB  0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 20  [emitted]         wfst, wms, mb-bright, bookmark, geolocation, realtime, paint-change, legends, filter, export-image, drawing, basic, upload-map, sprite-animation, popups, feature-table, basic-wgs84, sprites, rotating, clustering
                              build/examples/wms/wms.bundle.js    3.39 MB                                                                     1  [emitted]  [big]  wms
                                    build/examples/sdk.css.map  502 bytes  0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 20  [emitted]         wfst, wms, mb-bright, bookmark, geolocation, realtime, paint-change, legends, filter, export-image, drawing, basic, upload-map, sprite-animation, popups, feature-table, basic-wgs84, sprites, rotating, clustering
                          build/examples/wms/wms.bundle.js.map    3.69 MB                                                                     1  [emitted]         wms
              build/examples/mb-bright/mb-bright.bundle.js.map    3.65 MB                                                                     2  [emitted]         mb-bright
                build/examples/bookmark/bookmark.bundle.js.map    3.65 MB                                                                     3  [emitted]         bookmark
          build/examples/geolocation/geolocation.bundle.js.map    3.65 MB                                                                     4  [emitted]         geolocation
                build/examples/realtime/realtime.bundle.js.map    3.63 MB                                                                     5  [emitted]         realtime
        build/examples/paint-change/paint-change.bundle.js.map    3.65 MB                                                                     6  [emitted]         paint-change
                  build/examples/legends/legends.bundle.js.map    3.65 MB                                                                     7  [emitted]         legends
                    build/examples/filter/filter.bundle.js.map    3.64 MB                                                                     8  [emitted]         filter
        build/examples/export-image/export-image.bundle.js.map    3.63 MB                                                                     9  [emitted]         export-image
                  build/examples/drawing/drawing.bundle.js.map    3.64 MB                                                                    10  [emitted]         drawing
                      build/examples/basic/basic.bundle.js.map    3.64 MB                                                                    11  [emitted]         basic
            build/examples/upload-map/upload-map.bundle.js.map    3.63 MB                                                                    12  [emitted]         upload-map
build/examples/sprite-animation/sprite-animation.bundle.js.map    3.63 MB                                                                    13  [emitted]         sprite-animation
                    build/examples/popups/popups.bundle.js.map    3.64 MB                                                                    14  [emitted]         popups
      build/examples/feature-table/feature-table.bundle.js.map    3.64 MB                                                                    15  [emitted]         feature-table
          build/examples/basic-wgs84/basic-wgs84.bundle.js.map    3.64 MB                                                                    16  [emitted]         basic-wgs84
                  build/examples/sprites/sprites.bundle.js.map    3.63 MB                                                                    17  [emitted]         sprites
                build/examples/rotating/rotating.bundle.js.map    3.63 MB                                                                    18  [emitted]         rotating
            build/examples/layer-list/layer-list.bundle.js.map    3.64 MB                                                                    19  [emitted]         layer-list
            build/examples/clustering/clustering.bundle.js.map    3.63 MB                                                                    20  [emitted]         clustering
 [434] multi (webpack)-dev-server/client?http://localhost:3000 webpack/hot/dev-server webpack/hot/only-dev-server ./examples/feature-table/app.js 64 bytes {15} [built]
 [437] multi (webpack)-dev-server/client?http://localhost:3000 webpack/hot/dev-server webpack/hot/only-dev-server ./examples/filter/app.js 64 bytes {8} [built]
 [440] multi (webpack)-dev-server/client?http://localhost:3000 webpack/hot/dev-server webpack/hot/only-dev-server ./examples/geolocation/app.js 64 bytes {4} [built]
 [445] multi (webpack)-dev-server/client?http://localhost:3000 webpack/hot/dev-server webpack/hot/only-dev-server ./examples/layer-list/app.js 64 bytes {19} [built]
 [447] multi (webpack)-dev-server/client?http://localhost:3000 webpack/hot/dev-server webpack/hot/only-dev-server ./examples/legends/app.js 64 bytes {7} [built]
 [449] multi (webpack)-dev-server/client?http://localhost:3000 webpack/hot/dev-server webpack/hot/only-dev-server ./examples/mb-bright/app.js 64 bytes {2} [built]
 [451] multi (webpack)-dev-server/client?http://localhost:3000 webpack/hot/dev-server webpack/hot/only-dev-server ./examples/paint-change/app.js 64 bytes {6} [built]
 [453] multi (webpack)-dev-server/client?http://localhost:3000 webpack/hot/dev-server webpack/hot/only-dev-server ./examples/popups/app.js 64 bytes {14} [built]
 [455] multi (webpack)-dev-server/client?http://localhost:3000 webpack/hot/dev-server webpack/hot/only-dev-server ./examples/realtime/app.js 64 bytes {5} [built]
 [457] multi (webpack)-dev-server/client?http://localhost:3000 webpack/hot/dev-server webpack/hot/only-dev-server ./examples/rotating/app.js 64 bytes {18} [built]
 [459] multi (webpack)-dev-server/client?http://localhost:3000 webpack/hot/dev-server webpack/hot/only-dev-server ./examples/sprite-animation/app.js 64 bytes {13} [built]
 [461] multi (webpack)-dev-server/client?http://localhost:3000 webpack/hot/dev-server webpack/hot/only-dev-server ./examples/sprites/app.js 64 bytes {17} [built]
 [463] multi (webpack)-dev-server/client?http://localhost:3000 webpack/hot/dev-server webpack/hot/only-dev-server ./examples/upload-map/app.js 64 bytes {12} [built]
 [466] multi (webpack)-dev-server/client?http://localhost:3000 webpack/hot/dev-server webpack/hot/only-dev-server ./examples/wfst/app.js 64 bytes {0} [built]
 [493] multi (webpack)-dev-server/client?http://localhost:3000 webpack/hot/dev-server webpack/hot/only-dev-server ./examples/wms/app.js 64 bytes {1} [built]
    + 490 hidden modules

ERROR in ./examples/mb-bright/app.js
Module not found: Error: Can't resolve './conf' in '/home/kratos/Developments/AMA/sdk/examples/mb-bright'
 @ ./examples/mb-bright/app.js 55:12-29
 @ multi (webpack)-dev-server/client?http://localhost:3000 webpack/hot/dev-server webpack/hot/only-dev-server ./examples/mb-bright/app.js

ERROR in ./examples/realtime/app.js
Module not found: Error: Can't resolve './conf' in '/home/kratos/Developments/AMA/sdk/examples/realtime'
 @ ./examples/realtime/app.js 43:12-29
 @ multi (webpack)-dev-server/client?http://localhost:3000 webpack/hot/dev-server webpack/hot/only-dev-server ./examples/realtime/app.js
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js!node_modules/sass-loader/lib/loader.js??ref--1-3!examples/wfst/app.css:
       [0] ./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js?{"includePaths":["node_modules"]}!./examples/wfst/app.css 748 bytes {0} [built]
       [1] ./node_modules/css-loader/lib/css-base.js 2.26 kB {0} [built]
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js!node_modules/sass-loader/lib/loader.js??ref--1-3!src/stylesheet/sdk.scss:
       [0] ./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js?{"includePaths":["node_modules"]}!./src/stylesheet/sdk.scss 9.76 kB {0} [built]
       [1] ./node_modules/css-loader/lib/css-base.js 2.26 kB {0} [built]
webpack: Failed to compile.

**Comment by bartvde** [comment]
create a conf.js file for those examples with your mapbox api key in it:

something like: ```module.exports = {
  'access_token': 'your_key_here’
};
```

**Comment by bartvde** [comment]
I will make sure we update our docs with this info

**Comment by kratosmat** [comment]
HI Bart,
after added the file conf.js as follow:

module.exports = {
    "access_token": "<key>"
};

It is working now, thanks a lot, and you are right, could be better if you
add these instructions on the documentation.

I have a last question for you: I have used the version 1 of sdk and there
were a lot of components, examples and complete documentation, why I can't
find the same support for version 2?



Matteo Cusmai

**Comment by bartvde** [comment]
the focus of v2 is different, where v1 was a widget library, v2 is trying not to be opinionated on the UI (if we use UI, it's plain HTML elements that can be overridden). So it's more about doing the core right (mapbox style document based mapping). So v1 only has a minimal UI.

**Comment by bartvde** [comment]
As for the docs, this is the stuff we have right now: https://sdk.boundlessgeo.com/docs/

If you have ideas on what is missing, let me know

**Comment by kratosmat** [comment]
Hi Bart,
so the version 2 of the SDK isn't a widget library to develop a complete
webgis application?

So, how can I use the SDK to develop a webgis application? Do I have to
develop all widgets such as measurements, select of basemap, drawing
features, feature table, and so on?


Matteo Cusmai

**Comment by bartvde** [comment]
If you look at the examples, a lot of the code for this is already in sdk (just not the UI to operate it), e.g. check the draw example for the measure and draw functionality: https://sdk.boundlessgeo.com/drawing/index.html
